package com.example.securefolder.utils;

import java.io.InputStream;
import java.io.OutputStream;
import javax.crypto.Cipher;
import javax.crypto.CipherInputStream;
import javax.crypto.CipherOutputStream;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;

/**
 * CryptoManager
 * Handles AES-GCM Encryption and Decryption streams.
 */
public class CryptoManager {

    private static final String ALGORITHM = "AES/GCM/NoPadding";
    private static final int IV_LENGTH = 12; // Recommended for GCM
    private static final int TAG_LENGTH = 128;

    /**
     * Encrypts data from inputStream and writes to outputStream.
     * Format: [IV (12 bytes)] + [Encrypted Data]
     */
    public static boolean encrypt(SecretKey key, InputStream inputStream, OutputStream outputStream) {
        try {
            Cipher cipher = Cipher.getInstance(ALGORITHM);
            cipher.init(Cipher.ENCRYPT_MODE, key);

            // 1. Get the random IV generated by the cipher
            byte[] iv = cipher.getIV();

            // 2. Write IV to the beginning of the file
            outputStream.write(iv);

            // 3. Write Encrypted Data
            CipherOutputStream cipherOutputStream = new CipherOutputStream(outputStream, cipher);
            byte[] buffer = new byte[1024]; // 1KB buffer
            int bytesRead;
            while ((bytesRead = inputStream.read(buffer)) != -1) {
                cipherOutputStream.write(buffer, 0, bytesRead);
            }

            cipherOutputStream.close();
            inputStream.close();
            outputStream.close();
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Decrypts data from inputStream and writes to outputStream.
     * Expects Format: [IV (12 bytes)] + [Encrypted Data]
     */
    public static boolean decrypt(SecretKey key, InputStream inputStream, OutputStream outputStream) {
        try {
            // 1. Read the IV from the start of the file
            byte[] iv = new byte[IV_LENGTH];
            int ivRead = inputStream.read(iv);
            if (ivRead != IV_LENGTH) return false; // File too short or corrupted

            // 2. Initialize Cipher
            Cipher cipher = Cipher.getInstance(ALGORITHM);
            GCMParameterSpec spec = new GCMParameterSpec(TAG_LENGTH, iv);
            cipher.init(Cipher.DECRYPT_MODE, key, spec);

            // 3. Read and Decrypt Data
            CipherInputStream cipherInputStream = new CipherInputStream(inputStream, cipher);
            byte[] buffer = new byte[1024];
            int bytesRead;
            while ((bytesRead = cipherInputStream.read(buffer)) != -1) {
                outputStream.write(buffer, 0, bytesRead);
            }

            cipherInputStream.close();
            inputStream.close();
            outputStream.close();
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
}